# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.0.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files

# Run pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.1.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus]

# Black
- repo: https://github.com/psf/black
  rev: 19.10b0
  hooks:
  -  id: black

# Flake 8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
  - id: flake8
    args: [--config, setup.cfg]
    # TODO: don't duplicate with requirements-lint.txt
    additional_dependencies:
    - flake8-bugbear==20.1.4
    - flake8-docstrings==1.5.0
    - flake8-isort==2.8.0
    - pydocstyle==5.0.2
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
